### PR TITLE
Win

### PR DESCRIPTION
**Pull request by ocefpaf**
@xhochy if this works are you OK doing a repackage here? It is the same we do with `rgdal` BTW.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Failing with:


```
cp: unknown option -- )
Try '/usr/bin/cp --help' for more information.
ERROR: installing binary package failed
```

I have to confess that I'm lost there :-/

**Comment by xhochy** [comment]
> @xhochy if this works are you OK doing a repackage here? It is the same we do with `rgdal` BTW.

If it works, I'm ok with this.

**Comment by ocefpaf** [comment]
> If it works, I'm ok with this.

OK. "Installing: it works locally but we need to manually move stuff to get it to work with conda PREFIXes. Ready for a review!

**Comment by ocefpaf** [comment]
@xhochy this is ready for a review!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
